<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="sebin" failures="1" tests="2" name="Test" time="0.165" errors="0" timestamp="2025-01-31T10:30:15 IST">
  <testcase classname="com.ospyn.ktu.test.Database" name="@AfterMethod getResult" time="0.11">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.ospyn.ktu.util.GenerateExtentReport.addScreenShotToLog(String)&amp;quot; because &amp;quot;com.ospyn.ktu.test.Database.report&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.ospyn.ktu.util.GenerateExtentReport.addScreenShotToLog(String)" because "com.ospyn.ktu.test.Database.report" is null
at com.ospyn.ktu.test.Database.getResult(Database.java:88)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod getResult -->
  <testcase classname="com.ospyn.ktu.test.Database" name="@AfterMethod getResult" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod getResult -->
  <testcase classname="com.ospyn.ktu.test.Database" name="Login_as_AdExa" time="0.004">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="Index 1 out of bounds for length 1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at com.ospyn.ktu.test.Database.Login_as_AdExa(Database.java:109)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- Login_as_AdExa -->
  <testcase classname="com.ospyn.ktu.test.Database" name="db" time="0.0">
    <skipped/>
  </testcase> <!-- db -->
</testsuite> <!-- Test -->
